services:
  netbox:
    image: netboxcommunity/netbox:latest
    depends_on:
      - postgres
      - redis
    ports:
      - "8500:8080"
    volumes:
      - netbox-static-files:/opt/netbox/netbox/static
      - netbox-media-files:/opt/netbox/netbox/media
    environment:
      # Netbox configuration
      - SUPERUSER_USERNAME=admin
      - SUPERUSER_PASSWORD=admin123
      - SUPERUSER_EMAIL=admin@example.com
      - SUPERUSER_API_TOKEN=0123456789abcdef0123456789abcdef01234567
      # Database configuration
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=netbox
      - DB_USER=netbox
      - DB_PASSWORD=securepassword123
      # Redis configuration
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redissecure123
      # Secret key (generate a unique one for production)
      - SECRET_KEY=2vym+ky!j+djr0ddsquf0#b%7g$m^p%es3b)g=m_m3v%98u%ak
      # Allowed hosts
      - ALLOWED_HOSTS=localhost,127.0.0.1
      # Other configurations
      - NAPALM_USERNAME=admin
      - NAPALM_PASSWORD=admin123
      - TIME_ZONE=UTC

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=netbox
      - POSTGRES_USER=netbox
      - POSTGRES_PASSWORD=securepassword123
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: redis-server --requirepass redissecure123
    volumes:
      - redis-data:/data

volumes:
  netbox-static-files:
  netbox-media-files:
  postgres-data:
  redis-data:
